version: '3'

services:
  app_spdle:
    build: southparkdle-backend
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://soutparkdle_bd:3306/southparkdle
      DB_USER_NAME: root
      DB_PASSWORD: jilguero1
    restart: always
    depends_on:
      soutparkdle_bd:
          condition: service_healthy
  soutparkdle_bd:
    image: mysql:8.3.0 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: jilguero1
      MYSQL_PASSWORD: jilguero1
      MYSQL_DATABASE: southparkdle
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10